server.port=8081
sprint.application.name=sturdy-octo-potato
spring.data.mongodb.uri=${MONGODB_CONNECTION_STRING}
spring.data.mongodb.auto-index-creation=true
jwt.secret=${JWT_SECRET_BASE64}
jwt.expiration=15
